name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  go-tests:
    name: Run Go tests with coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run Go coverage checks
        shell: bash
        run: make test-coverage
